version: '2'

services:
    remark:
        image: umputun/docker-logger
        container_name: "logger"
        hostname: "logger"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        environment:
            - MHOST
            - LOG_FILES=true
            - LOG_SYSLOG=false
            - EXCLUDE=monit,docker-logger
            - MAX_FILES=10
            - MAX_SIZE=50
            - MAX_AGE=20
            - DEBUG=false
            - TIME_ZONE=America/Chicago

        volumes:
            - ./logs:/srv/logs
            - /var/run/docker.sock:/var/run/docker.sock
       